export default function LinksPage() {
    // 自定义你的常用链接
    const links = [
        { name: 'GitHub 个人主页', url: 'https://ychda.github.io', desc: '个人 GitHub 主页' },
        {name: 'GitHub', url: 'https://github.com/ychda', desc: '代码托管平台'},
        {name: 'Next.js 官网', url: 'https://nextjs.org', desc: 'React 服务端渲染框架'},
        {name: '掘金', url: 'https://juejin.cn', desc: '技术博客社区'},
        {name: 'TypeScript 官网', url: 'https://www.typescriptlang.org', desc: 'JS 类型系统'},
        {name: 'Tailwind CSS', url: 'https://tailwindcss.com', desc: '实用优先 CSS 框架'},
        { name: 'Vite', url: 'https://vite.dev/', desc: '下一代前端构建工具' },
        { name: 'Git 官方书籍', url: 'https://git-scm.com/book/zh/v2', desc: 'Git 中文官方教程' },
        { name: 'GitHub 账号', url: 'https://github.com/ychda', desc: 'GitHub 仓库主页' },
        { name: 'Kotlin', url: 'https://kotlinlang.org/', desc: 'Kotlin 编程语言官网' },
        { name: 'Django 文档', url: 'https://docs.djangoproject.com/zh-hans/5.0/', desc: 'Django 5.0 官方中文文档' },
        { name: 'Scrapy', url: 'https://scrapy.org/', desc: 'Python 爬虫框架' },
        { name: 'Node.js', url: 'https://nodejs.org/zh-cn', desc: 'Node.js 中文官网' },
        { name: 'VitePress', url: 'https://vitepress.vuejs.org/', desc: 'Vue 静态文档站点框架' },
        { name: 'MDN Web Docs', url: 'https://developer.mozilla.org/zh-CN/docs/Web', desc: '前端权威文档 MDN' },
        { name: 'Google Fonts', url: 'https://fonts.google.com/', desc: '谷歌免费字体库' },
        { name: '菜鸟教程', url: 'https://www.runoob.com/', desc: '编程入门教程网站' },
        { name: '百度前端技术学园', url: 'https://ife.baidu.com/', desc: '百度前端学习资源' },
        { name: 'Project Euler', url: 'https://projecteuler.net/archives', desc: '数学编程题库' },
        { name: 'LeetCode 国际版', url: 'https://leetcode.com/problemset/all/', desc: '算法刷题平台' },
        { name: 'The Big Read', url: 'https://en.wikipedia.org/wiki/The_Big_Read?wprov=sfla1', desc: 'BBC 百大阅读书单' },
        { name: 'Markdown 教程', url: 'https://markdown.com.cn/', desc: 'Markdown 语法中文教程' },
        { name: 'GitHub Markdown 文档', url: 'https://docs.github.com/cn/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax', desc: 'GitHub Markdown 语法规范' },
        { name: 'vi 命令教程', url: 'https://www.cs.colostate.edu/helpdocs/vi.html', desc: 'vi 编辑器命令大全' },
        { name: 'Java 核心技术', url: 'https://horstmann.com/corejava/', desc: 'Java 经典书籍官网' },
        { name: 'Guido van Rossum', url: 'https://gvanrossum.github.io/', desc: 'Python 之父个人主页' },
        { name: '中国哲学书电子化计划', url: 'https://ctext.org/zh', desc: '古籍在线阅览平台' },
        { name: 'WolframAlpha', url: 'https://www.wolframalpha.com/', desc: '智能数学计算引擎' },
        { name: 'Hacking CPP', url: 'https://hackingcpp.com/', desc: 'C++ 进阶学习网站' },
        { name: 'Stylus', url: 'https://stylus-lang.com/', desc: 'CSS 预处理器' },
        { name: 'Compiler Explorer', url: 'https://godbolt.org/', desc: '在线汇编编译器' },
        { name: 'Photoshop 学习', url: 'https://helpx.adobe.com/cn/support/photoshop-china.html', desc: 'Adobe Photoshop 官方支持文档' },
        { name: 'Animate.css', url: 'https://animate.style/', desc: '常用 CSS 动画库' },
        { name: 'Apache ECharts', url: 'https://echarts.apache.org/zh/index.html', desc: '开源可视化图表库' },
        { name: 'Arduino 编程', url: 'https://docs.arduino.cc/programming/', desc: 'Arduino 开发文档' },
        { name: 'AutoCAD 命令', url: 'http://localhost:8000/autocad/', desc: 'AutoCAD 命令参考' },
        { name: 'BBC The Big Read', url: 'https://www.bbc.co.uk/arts/bigread/', desc: 'BBC 经典阅读推荐' },
        { name: 'Babel', url: 'https://babeljs.io/', desc: 'JavaScript 转译编译器' },
        { name: 'BootCDN', url: 'https://www.bootcdn.cn/', desc: '开源静态资源 CDN' },
        { name: 'Bootstrap Icons', url: 'https://icons.getbootstrap.com/', desc: 'Bootstrap 官方图标库' },
        { name: 'Bootstrap 布局', url: 'https://getbootstrap.com/docs/5.3/utilities/display/', desc: 'Bootstrap 工具类文档' },
        { name: 'Django 表单教程', url: 'https://www.twilio.com/blog/build-contact-form-python-django-twilio-sendgrid', desc: 'Django 联系表单开发' },
        { name: 'CSS 权威指南', url: 'https://meyerweb.github.io/csstdg4figs/index.html', desc: 'CSS 权威指南配图与资料' },
        { name: 'CSS 参考手册', url: 'https://developer.mozilla.org/zh-CN/docs/Web/CSS/Reference', desc: 'MDN CSS 属性大全' },
        { name: 'CSS-Tricks', url: 'https://css-tricks.com/', desc: 'CSS 技巧与教程网站' },
        { name: 'CSS 钟表示例', url: 'https://css-tricks.com/creating-a-clock-with-the-new-css-sin-and-cos-trigonometry-functions/', desc: 'CSS 三角函数实现时钟' },
        { name: 'CodePen', url: 'https://codepen.io', desc: '前端在线代码演示' },
        { name: 'DevDocs', url: 'https://devdocs.io/', desc: '聚合 API 文档查阅' },
        { name: 'Django REST Framework', url: 'https://www.django-rest-framework.org/', desc: 'Django API 开发框架' },
        { name: 'Django 官方中文文档', url: 'https://docs.djangoproject.com/zh-hans/', desc: 'Django 全套中文文档' },
        { name: 'DjangoCentral', url: 'https://djangocentral.com/', desc: 'Django 教程资源站' },
        { name: 'DjangoGirls', url: 'https://github.com/DjangoGirls/djangogirls/tree/main', desc: 'Django 入门公益教程' },
        { name: 'ESLint', url: 'https://eslint.org/', desc: 'JavaScript 代码检查工具' },
        { name: 'EditPlus', url: 'https://www.editplus.com/index.html', desc: '轻量级代码编辑器' },
        { name: 'Eric A. Meyer', url: 'https://meyerweb.com/', desc: 'CSS 权威指南作者主页' },
        { name: '书籍分级阅读', url: 'https://bookroo.com/explore/books/lexile-levels', desc: 'Lexile 分级阅读书目' },
        { name: 'Freenode', url: 'https://freenode.me/f/freenode', desc: '开源社区 IRC 网络' },
        { name: 'GitHub Markdown 规范', url: 'https://github.github.com/gfm/', desc: 'GFM 标准规范' },
        { name: 'MDN 学习仓库', url: 'https://github.com/mdn/learning-area/tree/main', desc: 'MDN 前端示例代码' },
        { name: 'Grid 布局示例', url: 'https://gridbyexample.com/', desc: 'CSS Grid 实战教程' },
        { name: 'JSON 编解码文档', url: 'https://docs.python.org/3/library/json.html', desc: 'Python JSON 标准库' },
        { name: 'JSONPlaceholder', url: 'https://jsonplaceholder.typicode.com/guide/', desc: '免费模拟 JSON 接口' },
        { name: 'JSON.org', url: 'https://www.json.org/json-zh.html', desc: 'JSON 官方中文介绍' },
        { name: 'Lea Verou', url: 'https://lea.verou.me/', desc: 'CSS 技术大牛博客' },
        { name: '力扣 LeetCode', url: 'https://leetcode.cn/', desc: '国内算法刷题平台' },
        { name: 'Lorem Picsum', url: 'https://picsum.photos/', desc: '免费图片占位服务' },
        { name: 'MDN CSS 教程', url: 'https://developer.mozilla.org/zh-CN/docs/Web/CSS', desc: 'MDN CSS 完整教程' },
        { name: 'Django 本地库教程', url: 'https://developer.mozilla.org/zh-CN/docs/Learn/Server-side/Django', desc: 'MDN Django 入门' },
        { name: 'MSDN 我告诉你', url: 'https://msdn.itellyou.cn/', desc: '开发软件镜像下载' },
        { name: 'MASM 汇编', url: 'https://learn.microsoft.com/zh-cn/cpp/assembler/masm/directives-reference?view=msvc-170', desc: '微软宏汇编器文档' },
        { name: 'NASM 汇编入门', url: 'https://blog.csdn.net/qq_52300431/article/details/127397862', desc: 'NASM 汇编零基础教程' },
        { name: 'Next.js 文档', url: 'https://nextjs.org/docs', desc: 'Next.js 官方开发文档' },
        { name: 'Photoshop 快速入门', url: 'https://helpx.adobe.com/cn/photoshop/get-started.html', desc: 'PS 新手入门指南' },
        { name: 'Placehold 占位图', url: 'https://placehold.co/', desc: '简洁图片占位服务' },
        { name: 'ProjectEuler 题库', url: 'https://projecteuler.net/', desc: '数学编程挑战题库' },
        { name: 'Pygments', url: 'https://pygments.org/', desc: '代码语法高亮工具' },
        { name: 'Python Challenge', url: 'http://www.pythonchallenge.com/', desc: 'Python 解谜闯关' },
        { name: 'Python 官网', url: 'https://docs.python.org/zh-cn/3/', desc: 'Python 3 中文文档' },
        { name: 'RuTracker', url: 'https://rutracker.org/forum/index.php', desc: '资源索引论坛' },
        { name: 'Tailwind CSS', url: 'https://tailwindcss.com/', desc: '实用优先 CSS 框架' },
        { name: 'Vue.js', url: 'https://cn.vuejs.org/', desc: 'Vue 中文官网' },
        { name: 'W3Schools', url: 'https://www.w3schools.com/css/default.asp', desc: 'Web 入门教程站' },
        { name: 'Word Frequency', url: 'https://www.wordfrequency.info/', desc: '英语词频查询' },
        { name: 'Codecademy', url: 'https://www.codecademy.com/catalog/subject/web-development', desc: '在线交互式编程学习' },
        { name: 'Django 评论模型教程', url: 'https://tutorial-extensions.djangogirls.org/en/homework_create_more_models/', desc: 'Django 自定义模型开发' },
        { name: 'Django Markdown 教程', url: 'https://learndjango.com/tutorials/django-markdown-tutorial', desc: 'Django 集成 Markdown' },
        { name: 'django-mdeditor', url: 'https://pypi.org/project/django-mdeditor/', desc: 'Django Markdown 编辑器插件' },
        { name: 'djangocms-blog', url: 'https://djangocms-blog.readthedocs.io/en/latest/features/channels.html', desc: 'DjangoCMS 博客插件' },
        { name: '开源软件 FAQ', url: 'https://dodcio.defense.gov/Open-Source-Software-FAQ/', desc: '开源软件许可常见问题' },
        { name: 'EasyX', url: 'https://docs.easyx.cn/zh-cn/intro', desc: 'C++ 图形编程库' },
        { name: 'freeCodeCamp', url: 'https://www.freecodecamp.org/', desc: '免费全栈编程学习' },
        { name: 'freeCodeCamp 样式指南', url: 'https://design-style-guide.freecodecamp.org/', desc: '前端代码风格规范' },
        { name: 'Flexbox 完整指南', url: 'https://css-tricks.com/snippets/css/a-guide-to-flexbox/', desc: 'CSS Flexbox 布局教程' },
        { name: 'Flexbox 游戏', url: 'https://flexboxfroggy.com/', desc: '趣味游戏学习 Flexbox' },
        { name: 'Imgur 图床', url: 'https://imgur.com/', desc: '免费图片托管服务' },
        { name: 'Real Python Django 博客', url: 'https://realpython.com/python-django-blog/', desc: 'Django 博客开发实战教程' },
        { name: 'Scratch 编程', url: 'https://scratch.mit.edu/', desc: '少儿图形化编程平台' },
        { name: 'Stackblitz', url: 'https://stackblitz.com/', desc: '在线前端开发环境' },
        { name: 'HTML 转 JSX 工具', url: 'https://transform.tools/html-to-jsx', desc: '在线转换 HTML 为 JSX' },
        { name: 'Web.dev CSS 教程', url: 'https://web.dev/learn/css/', desc: '谷歌官方 CSS 学习指南' },
        { name: 'Web.dev HTML 教程', url: 'https://web.dev/learn/html/', desc: '谷歌官方 HTML 学习指南' },
        { name: '网页字体资源', url: 'https://web.mit.edu/jmorzins/www/fonts.html', desc: '经典 Web 字体参考' },
        { name: 'Whitenoise', url: 'https://whitenoise.readthedocs.io/en/stable/django.html#django-middleware', desc: 'Django 静态文件优化中间件' },
        { name: 'PS 资源教程', url: 'https://www.superso.top/Adobe/Adobe_Photoshop_2022.html', desc: 'Photoshop 资源合集与教程' },
        { name: '现代JavaScript教程', url: 'https://zh.javascript.info/', desc: '现代 JavaScript 中文教程' },
        { name: 'Medium', url: 'https://medium.com/', desc: '海外优质技术博客平台' },
        { name: 'React 中文官网', url: 'https://zh-hans.react.dev/', desc: 'React 官方中文文档' },
        { name: 'Stack Overflow', url: 'https://stackoverflow.com/questions/tagged/scrapy', desc: '全球技术问答社区' },
        { name: 'Toscrape', url: 'https://toscrape.com/', desc: '爬虫实战练习测试网站' },
        { name: 'Udemy', url: 'https://www.udemy.com/', desc: '海外精品在线课程平台' },
        { name: 'v2rayNG', url: 'https://github.com/2dust/v2rayNG/releases', desc: '安卓网络工具客户端' },
        { name: '应急管理部', url: 'https://cx.mem.gov.cn/', desc: '中华人民共和国应急管理部官网' },
        { name: '小学信息技术资源', url: 'https://www.pep.com.cn/xxjs/rjbxxjs/rjxxjswd/201909/t20190929_1945792.html', desc: '人教社信息技术配套资源下载' },
        { name: '人教社课本电子版', url: 'https://jc.pep.com.cn/', desc: '中小学教材电子版查阅' },
        { name: '侃单片机论坛', url: 'https://bbs.21ic.com/icfilter-typeid-11-211.html', desc: '单片机技术交流社区' },
        { name: '国芯论坛', url: 'https://www.stcaimcu.com/', desc: '国产芯片技术交流平台' },
        { name: '安信可开发工具', url: 'https://docs.ai-thinker.com/%E5%BC%80%E5%8F%91%E5%B7%A5%E5%85%B72', desc: '安信可模组开发官方资料' },
        { name: 'CAD 练习图', url: 'https://zhuanlan.zhihu.com/p/62979867', desc: '50 张常用 CAD 平面练习图纸' },
        { name: '微信读书', url: 'https://weread.qq.com/', desc: '腾讯微信读书平台' },
        { name: '数据结构与算法', url: 'https://c.biancheng.net/data_structure/', desc: '数据结构与算法入门教程' },
        { name: '新概念英语', url: 'https://www.runtoenglish.com/', desc: '新概念英语学习资源站点' },
        { name: '普中科技', url: 'http://www.prechin.cn/', desc: '单片机开发板厂商官网' },
        { name: '汇编语言教程', url: 'https://www.cainiaoya.com/assemblylanguage/assembly-language-introduction.html', desc: '汇编语言零基础入门教程' },
        { name: '深圳国芯人工智能', url: 'https://www.stcai.com/', desc: '国芯AI与芯片公司官网' },
        { name: 'IP 地址计算器', url: 'https://iiis.tsinghua.edu.cn/ip/', desc: '网络子网IP地址计算工具' },
        { name: 'Django 自定义模板标签', url: 'https://docs.djangoproject.com/zh-hans/5.2/howto/custom-template-tags/', desc: 'Django 模板标签与过滤器开发' },
        { name: '课程表作息表', url: 'https://ychda.github.io/yhz/2023b.html', desc: '在线课程表与作息时间表' },
        { name: '前端学习路线', url: 'https://developer.aliyun.com/learning/roadmap/frontend', desc: '阿里云前端工程师成长路线' },
    ];    return (
        <div className="space-y-6">
            <h1 className="text-3xl font-bold">常用链接</h1>
            <div className="grid gap-4 md:grid-cols-2">
                {links.map((link, index) => (
                    <a
                        key={index}
                        href={link.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="p-4 border rounded-lg hover:border-blue-400 transition-colors"
                    >
                        <h3 className="font-medium text-blue-600">{link.name}</h3>
                        <p className="text-sm text-gray-600 mt-1">{link.desc}</p>
                    </a>
                ))}
            </div>
        </div>
    );
}
